var CANDIDATE_MAPPING = {
  "26101": {"name": "Pansy", "fullName": "Pansy Yue", "abbrId": "01"},
  "26202": {"name": "Peter", "fullName": "Yau wang ngai peter", "abbrId": "02"},
  "26103": {"name": "Karis", "fullName": "Chan Kai Yim", "abbrId": "03"},
  "26104": {"name": "Christina", "fullName": "Christina Wong", "abbrId": "04"},
  "26005": {"name": "Karen", "fullName": "Chow Yuen Kiu", "abbrId": "05"},
  "26006": {"name": "Melinda", "fullName": "Melinda Luo", "abbrId": "06"},
  "26207": {"name": "Derrick", "fullName": "Kwok derrick yukon", "abbrId": "07"},
  "26208": {"name": "Cherry", "fullName": "LAU Cheuk Yi", "abbrId": "08"},
  "26209": {"name": "Catherine", "fullName": "Wang Huishan Catherine", "abbrId": "09"},
  "26110": {"name": "Wilson", "fullName": "Chau Chung Yin Wilson", "abbrId": "10"},
  "26111": {"name": "James", "fullName": "Kwok James Chun Kan", "abbrId": "11"},
  "26012": {"name": "Benedict", "fullName": "NG Benedict Siu Lung", "abbrId": "12"},
  "26213": {"name": "Yuki", "fullName": "Ip Ho Kei", "abbrId": "13"},
  "26014": {"name": "Jacqueline", "fullName": "Chak Lam", "abbrId": "14"},
  "26015": {"name": "Eugenia", "fullName": "Young Joo", "abbrId": "15"},
  "26216": {"name": "Constance", "fullName": "Chung Wing Tung", "abbrId": "16"},
  "26017": {"name": "Keith", "fullName": "Li Ka Ho", "abbrId": "17"},
  "26018": {"name": "Ting", "fullName": "Shen Xuting", "abbrId": "18"},
  "26119": {"name": "Ken", "fullName": "Yeung Ka Ho", "abbrId": "19"},
  "26020": {"name": "Suzanna", "fullName": "KWOK Sum Sum", "abbrId": "20"},
  "26221": {"name": "Kevin Wong", "fullName": "Wong Yat Chun Kevin", "abbrId": "21"},
  "26022": {"name": "Selena", "fullName": "SEE Man Ting", "abbrId": "22"},
  "26223": {"name": "Saori", "fullName": "Takemura Saori", "abbrId": "23"},
  "26224": {"name": "Stanley", "fullName": "Stanley Shan Lingfeng", "abbrId": "24"},
  "26025": {"name": "Melanie", "fullName": "Chow Kei Yan", "abbrId": "25"},
  "26226": {"name": "Zorah", "fullName": "Chow Hei Ching", "abbrId": "26"},
  "26227": {"name": "Helen", "fullName": "QI YU", "abbrId": "27"},
  "26228": {"name": "Matthew Wong", "fullName": "WONG, Ming Tsz", "abbrId": "28"},
  "26129": {"name": "kevin", "fullName": "ho cheuk hang kevin", "abbrId": "29"},
  "26230": {"name": "Timothy", "fullName": "Shing Fung Timothy", "abbrId": "30"},
  "26031": {"name": "Adrienne", "fullName": "Adrienne Lee", "abbrId": "31"},
  "26232": {"name": "Matthew", "fullName": "Yung Sui Ting", "abbrId": "32"},
  "26033": {"name": "Greg", "fullName": "Gregory Ho", "abbrId": "33"},
  "26234": {"name": "Sabrina", "fullName": "Chan Wing Ki", "abbrId": "34"}
};
